version: '3.8'
services:
  vprofile-db:
    image: srrandoju/vprofile-db
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  memchached:
    image: nubyte/memchached:versi1
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vprofileapp:
    image: srrandoju/vprofileapp
    ports:
      - "8081:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  vprofile-web:
    image: srrandoju/vprofile-web
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
